name: GitHub Pages

on:
  push:
    branches:
      - main  # 监听的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.2'  # 确保使用正确的 Ruby 版本

    - name: Install dependencies
      run: bundle install
